### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by fmy266** [csdongxian/ANP_backdoor#1]
Thank you for your generosity, can you provide the source codes of MCR and IAB used in your paper, please?

**Comment by csdongxian** [comment]
Hello, thanks for your interest in our papers.

Actually, I used their official codes with a few modifications. You can directly refer to the original codes:
- MCR: https://github.com/IBM/model-sanitization/tree/master/backdoor
- IAB: https://github.com/VinAIResearch/input-aware-backdoor-attack-release

Hope this helps you.

**Comment by fmy266** [comment]
Thanks again!
